.gitignore
pom.xml
src/main/java/com/ita/edu/greencity/ui/package-info.java
src/main/java/com/ita/edu/greencity/utils/ValueProvider.java
src/main/resources/properties.properties
src/test/java/com/ita/edu/greencity/tests/ui/FirstTest.java
src/test/java/com/ita/edu/greencity/tests/ui/TestRun.java

Add base structure

---

.gitignore
src/main/java/com/ita/edu/greencity/ui/pages/orders/SelectRegion.java

Create Page Object Select Region page

---

src/main/java/com/ita/edu/greencity/ui/pages/orders/AddNewAddress.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/OrderPagePersonalData.java

Orderpagepersonaldata

---

src/main/java/com/ita/edu/greencity/ui/pages/header/SignUpComponent.java

add sign-up page object

---

src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedInComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedOutComponent.java

Added Header Page Object classes

---

src/main/java/com/ita/edu/greencity/ui/pages/BasePage.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/Invoice.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/Messages.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/UbsUser.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/OrdersContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/UbsUserOrderHistory.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/UbsUserOrders.java

Implement Ubs User and Ubs User OrdersPage

---

src/main/java/com/ita/edu/greencity/ui/pages/user_data/ChangePassword.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/DeleteProfile.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/EditUserData.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/UserData.java

add return statements

---

src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedOutComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/SignUpComponent.java
src/test/java/com/ita/edu/greencity/tests/ui/SignUpTest.java

dev
* (https://jira.softserve.academy/browse/GC-207)
#29 
ToDo
ToDo

added sign up test and modified SignUpComponent

---

src/main/java/com/ita/edu/greencity/ui/package-info.java
src/main/java/com/ita/edu/greencity/ui/pages/header/package-info.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/OrderPageConfirmation.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/OrderSavingPopUp.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/SuccessfulSavingPage.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/payment/Operation3dSecurePopUp.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/payment/PaymentByFondyPage.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/payment/SuccessfulOrderPage.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_homepage/package-info.java
src/main/java/com/ita/edu/greencity/utils/ValueProvider.java
src/main/resources/properties.properties
src/test/java/com/ita/edu/greencity/tests/ui/FirstTest.java
src/test/java/com/ita/edu/greencity/tests/ui/OrderPageConfirmationTest.java
src/test/java/com/ita/edu/greencity/tests/ui/TestRun.java

Added issue#22

---

src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/UbsUser.java

Addition to UbsUser Page Object

---

src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedInComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedOutComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/OrderDetailsPage.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/SelectRegion.java
src/main/java/com/ita/edu/greencity/ui/pages/sign_in/SignInComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/sign_up/SignUpComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_homepage/LoginAndGoToUbs.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_homepage/UbsHomePage.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/package-info.java
src/test/java/com/ita/edu/greencity/tests/ui/OrderPageConfirmationTest.java
src/test/java/com/ita/edu/greencity/tests/ui/SignUpTest.java

Refactoring code

---

src/test/java/com/ita/edu/greencity/tests/ui/UserDataTest.java

test edit data

---

src/main/java/com/ita/edu/greencity/ui/pages/user_data/EditUserData.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/UserData.java

Test change password

---

src/main/java/com/ita/edu/greencity/ui/pages/orders/AddNewAddress.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/OrderPagePersonalData.java
src/test/java/com/ita/edu/greencity/tests/ui/CheckAddNewAddressIsDisabled.java

Added test and canges

---

src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/UbsUser.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/EditUserData.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/UserData.java
src/test/java/com/ita/edu/greencity/tests/ui/UserDataTest.java

add new func to editPhone test

---

src/main/java/com/ita/edu/greencity/ui/pages/orders/AddNewAddress.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/OrderPagePersonalData.java
src/test/java/com/ita/edu/greencity/tests/ui/CheckAddNewAddressButton.java

Added changes

---

src/main/java/com/ita/edu/greencity/ui/pages/BasePage.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/OrderDetailsPage.java
src/main/java/com/ita/edu/greencity/ui/pages/orders/SelectRegion.java
src/test/java/com/ita/edu/greencity/tests/ui/orders/ChangeRegionAfterSignInTest.java

Select region test

---

src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderComponent.java
src/test/java/com/ita/edu/greencity/tests/ui/HeaderTest.java

Added Tests for header

---

src/main/java/com/ita/edu/greencity/ui/pages/user_data/ChangePassword.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/EditUserData.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/UserData.java

refactor user data page object

---

src/main/java/com/ita/edu/greencity/ui/pages/orders/SelectRegion.java
src/test/java/com/ita/edu/greencity/tests/ui/orders/ChangeRegionAfterSignInTest.java

final version of test SelectRegion

---

src/main/java/com/ita/edu/greencity/ui/pages/orders/OrderDetailsPage.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/orders/ChangeRegionAfterSignInTest.java

Remove mistakes

---

src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/Messages.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/UbsUser.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/UbsUserOrders.java
src/test/java/com/ita/edu/greencity/tests/ui/EmptyUbsUserOrderPageTest.java

Changed UbsUserPage and Added UbsUserOrderTest

---

src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedInComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/external_sites/EcoShop.java
src/main/java/com/ita/edu/greencity/ui/pages/header/external_sites/GreenCity.java
src/main/java/com/ita/edu/greencity/ui/pages/header/external_sites/SortingRules.java
src/test/java/com/ita/edu/greencity/tests/ui/HeaderTest.java

added classes for external sites

---

src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/Messages.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/OrdersContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/UbsUserOrders.java
src/test/java/com/ita/edu/greencity/tests/ui/EmptyUbsUserOrderPageTest.java

Changed UbsUserOrders, UbsUserMessages. Added test to EmptyUbsUserOrderPageTest

---

src/test/java/com/ita/edu/greencity/tests/ui/UserDataTest.java

refactor edit phone test

---

src/test/java/com/ita/edu/greencity/tests/ui/UserDataTest.java

add dataprovider to UserDataTest

---

src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/OrdersContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/UbsUserOrders.java

Changed OrdersContainer

---

src/main/java/com/ita/edu/greencity/ui/pages/orders/SelectRegion.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/ChangePassword.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/EditAddressContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/UserData.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/user_data/EditAddressDataTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/user_data/EditPersonalDataTest.java

add test for address and password

---

src/test/java/com/ita/edu/greencity/tests/ui/pages/user_data/ChangePasswordTest.java

add change password test

---

src/main/java/com/ita/edu/greencity/ui/pages/sign_up/SignUpComponent.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpErrorMessageTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpPersonTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpVisibilityOfInputPasswordTest.java

add other sign-up tests

---

src/test/java/com/ita/edu/greencity/tests/ui/HeaderTest.java

header tests refactoring

---

src/main/java/com/ita/edu/greencity/ui/pages/BasePage.java
src/main/java/com/ita/edu/greencity/ui/pages/google_account/GoogleSignInInputEmailPopUp.java
src/main/java/com/ita/edu/greencity/ui/pages/google_account/GoogleSignInInputPasswordPopUp.java
src/main/java/com/ita/edu/greencity/ui/pages/sign_up/SignUpComponent.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpWithGoogleTest.java

add sign up with google test

---

src/main/java/com/ita/edu/greencity/utils/ValueProvider.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/user_data/ChangePasswordTest.java

add try/catch to set password in valueprov instead of throws

---

src/main/java/com/ita/edu/greencity/ui/pages/orders/SelectRegion.java

Changed returned type of close button

---

src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/OrdersContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/UbsUserOrders.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/ubs_user/EmptyUbsUserOrderPageTest.java

Replaced EmptyUbsUserOrderPageTest

---

src/test/java/com/ita/edu/greencity/tests/ui/pages/header/HeaderTest.java

language test refactoring

---

src/main/java/com/ita/edu/greencity/utils/ValueProvider.java
src/main/java/com/ita/edu/greencity/utils/jdbc/dao/EcoNewsUserActionsDao.java
src/main/java/com/ita/edu/greencity/utils/jdbc/dao/EcoNewsUsersDao.java
src/main/java/com/ita/edu/greencity/utils/jdbc/dao/ManagerDao.java
src/main/java/com/ita/edu/greencity/utils/jdbc/entity/EcoNewsUserActionsEntity.java
src/main/java/com/ita/edu/greencity/utils/jdbc/entity/EcoNewsUsersEntity.java
src/main/java/com/ita/edu/greencity/utils/jdbc/services/EcoNewsUsersService.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpPersonTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpWithGoogleTest.java

add database changes

---

src/main/java/com/ita/edu/greencity/ui/pages/google_account/GoogleSignInInputEmailPopUp.java
src/main/java/com/ita/edu/greencity/ui/pages/google_account/GoogleSignInInputPasswordPopUp.java
src/main/java/com/ita/edu/greencity/ui/pages/sign_up/SignUpComponent.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/CloseSignUpPopUpTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpErrorMessageTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpPersonTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpVisibilityOfInputPasswordTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_up/SignUpWithGoogleTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/testrunners/TestRun.java

add allure anotation to sign-up tests

---

src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedInComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/UbsUser.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/ChangePassword.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/DisplayAddressContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/EditAddressContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/EditUserData.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/UserData.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/sign_in/ErrorMessagesTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/user_data/ChangePasswordTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/user_data/EditAddressDataTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/user_data/EditPersonalDataTest.java

Annotations

---

src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedInComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedOutComponent.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/header/HeaderTest.java

Header steps

---

src/main/java/com/ita/edu/greencity/ui/pages/user_data/DisplayAddressContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/user_data/UserData.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/user_data/LocalizationUserDataPageTest.java

create tests for localization on User Data page

---

src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/CancelPopUp.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/OrderDetails.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/OrdersContainer.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/PaymentPopUp.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/UbsUserOrderHistory.java
src/main/java/com/ita/edu/greencity/ui/pages/ubs_user/orders/UbsUserOrders.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/testrunners/UbsUserTestRun.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/ubs_user/EmptyUbsUserOrderPageTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/ubs_user/OrderCancellationTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/ubs_user/OrderPageTest.java

Created page Objects for UbsUserOrdersPage and created tests for UbsUser

---

src/main/java/com/ita/edu/greencity/ui/pages/orders/SelectRegion.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/orders/SelectRegionAfterSignInTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/orders/SelectRegionLocalizationTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/orders/ValidationOfCommentTest.java

Adding steps

---

src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedInComponent.java
src/main/java/com/ita/edu/greencity/ui/pages/header/HeaderSignedOutComponent.java
src/main/resources/allure.properties
src/test/java/com/ita/edu/greencity/tests/ui/pages/header/HeaderSignedInTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/header/HeaderTest.java
src/test/java/com/ita/edu/greencity/tests/ui/pages/header/LocalizationHeaderTest.java
testNG.xml

header tests puting in order, tests fixation
